In [271]:
pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [272]:
import pandas as pd
import numpy as np

In [273]:
# Create a basic Series
s = pd.Series([10, 20, 30, 40, 50])

s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [274]:
s.dtype # Check the data type of the Series

dtype('int64')

In [275]:
s.values # Get the values of the Series as a NumPy array

array([10, 20, 30, 40, 50])

In [276]:
s.index # Get the index of the Series

RangeIndex(start=0, stop=5, step=1)

In [277]:
#assign a name to the column
s.name = 'Numbers'

In [278]:
s

0    10
1    20
2    30
3    40
4    50
Name: Numbers, dtype: int64

In [279]:
# Indexing: used to access specific elements in a Series. You can use integer-based indexing or label-based indexing.

s[0] # Access the first element of the Series

np.int64(10)

In [280]:
s[0:2] # Access the first two elements of the Series

0    10
1    20
Name: Numbers, dtype: int64

In [281]:
s[2:4] #

2    30
3    40
Name: Numbers, dtype: int64

In [282]:
# iloc -> Location based indexing
s.iloc[3]

np.int64(40)

In [283]:
s.iloc[0:3]

0    10
1    20
2    30
Name: Numbers, dtype: int64

In [284]:
# Python List
name = ['Utibe', 'Bassey', 'Inyang']

name

['Utibe', 'Bassey', 'Inyang']

In [285]:
index = ['apple', 'banana', 'grapes', 'oranges', 'strawberry']
s.index = index

s

apple         10
banana        20
grapes        30
oranges       40
strawberry    50
Name: Numbers, dtype: int64

In [286]:
s['grapes']

np.int64(30)

In [287]:
# Loc --> label-based indexing
s.loc['grapes']

np.int64(30)

In [288]:
s.loc['banana': 'oranges']

banana     20
grapes     30
oranges    40
Name: Numbers, dtype: int64

In [289]:
# Creating a Series Using Dictionary

fruit_protein = {
    'Avovado': 2.0,
    'Guava': 2.6,
    'Blackberries': 2.0,
    'Oranges': 0.9,
    'Banana': 1.1,
    'Apples': 0.3,
    'Kiwi': 1.1,
    'Udara': 1.7,
    'Mango': 0.8,
    'Cherries': 1.0
}

In [290]:
s2 = pd.Series(fruit_protein, name = 'Protein')

In [291]:
s2

Avovado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Udara           1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [292]:
# Conditional Selection (s2 greater than 1)

s2>1

Avovado          True
Guava            True
Blackberries     True
Oranges         False
Banana           True
Apples          False
Kiwi             True
Udara            True
Mango           False
Cherries        False
Name: Protein, dtype: bool

In [293]:
s2[s2>1]

Avovado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Udara           1.7
Name: Protein, dtype: float64

In [294]:
# Logical Operators (and, or, not)

[(s2>0.5) & (s2<2)]

[Avovado         False
 Guava           False
 Blackberries    False
 Oranges          True
 Banana           True
 Apples          False
 Kiwi             True
 Udara            True
 Mango            True
 Cherries         True
 Name: Protein, dtype: bool]

In [295]:
s2[(s2>0.5) & (s2<2)] # finding only the value that satisfy this condition

Oranges     0.9
Banana      1.1
Kiwi        1.1
Udara       1.7
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

In [296]:
s2[(s2>0.5) | (s2<2)] # Logical OR (|) operation

Avovado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Udara           1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [297]:
# Logical NOT Operation

s2[~(s2>1)] # finds all the values that are not greater than the value 1

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

In [298]:
s2[~(s2<1)] # finds all the values that are not less than the value 1

Avovado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Udara           1.7
Cherries        1.0
Name: Protein, dtype: float64

In [299]:
# MOdifying the series

s2['Mango'] = 2.8 # Modifies the value of mango from 0.8 to 2.8

In [300]:
s2

Avovado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Udara           1.7
Mango           2.8
Cherries        1.0
Name: Protein, dtype: float64

# DATAFRAME DATA STRUCTURE IN PANDAS

In [303]:
# DataFrame

data = {
    'Name': ['Utibe', 'Bassey', 'Inyang', 'Henry', 'Happiness', 'Hopex'],
    'Age':[30, 25, 20, np.nan, 29, 25],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
    'Salary': [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [304]:
data

{'Name': ['Utibe', 'Bassey', 'Inyang', 'Henry', 'Happiness', 'Hopex'],
 'Age': [30, 25, 20, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [305]:
# Converting the Python Dictionary (data) to a DataFrame
df = pd.DataFrame(data)
df

        Name   Age Department   Salary
0      Utibe  30.0         HR  50000.0
1     Bassey  25.0         IT  60000.0
2     Inyang  20.0    Finance  70000.0
3      Henry   NaN         IT  62000.0
4  Happiness  29.0         HR      NaN
5      Hopex  25.0         HR  50000.0

In [306]:
df.head(2) # --> Displays the first two rows

     Name   Age Department   Salary
0   Utibe  30.0         HR  50000.0
1  Bassey  25.0         IT  60000.0

In [307]:
df.tail(2) # Displays the last two rows

        Name   Age Department   Salary
4  Happiness  29.0         HR      NaN
5      Hopex  25.0         HR  50000.0

In [308]:
# Fetching the first and Second row in the dataset using the iloc and loc indexing

df.iloc[0:3]

     Name   Age Department   Salary
0   Utibe  30.0         HR  50000.0
1  Bassey  25.0         IT  60000.0
2  Inyang  20.0    Finance  70000.0

In [309]:
df.loc[0:3, ['Name','Age', 'Department']]

     Name   Age Department
0   Utibe  30.0         HR
1  Bassey  25.0         IT
2  Inyang  20.0    Finance
3   Henry   NaN         IT

In [310]:
df['Age'] # queries a single column

0    30.0
1    25.0
2    20.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [311]:
df[['Age', 'Department']]

    Age Department
0  30.0         HR
1  25.0         IT
2  20.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [312]:
df.head()

        Name   Age Department   Salary
0      Utibe  30.0         HR  50000.0
1     Bassey  25.0         IT  60000.0
2     Inyang  20.0    Finance  70000.0
3      Henry   NaN         IT  62000.0
4  Happiness  29.0         HR      NaN

In [313]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [314]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   25.800000  58400.000000
std     3.962323   8532.291603
min    20.000000  50000.000000
25%    25.000000  50000.000000
50%    25.000000  60000.000000
75%    29.000000  62000.000000
max    30.000000  70000.000000

In [315]:
# Broadcasting in pandas

df['Salary'] = df['Salary'] + 5000

df['Salary']

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [316]:
df

        Name   Age Department   Salary
0      Utibe  30.0         HR  55000.0
1     Bassey  25.0         IT  65000.0
2     Inyang  20.0    Finance  75000.0
3      Henry   NaN         IT  67000.0
4  Happiness  29.0         HR      NaN
5      Hopex  25.0         HR  55000.0

In [317]:
# Renaming Columns in a DataFrame

df.rename(columns={'Department': 'Dept'}, inplace= True)

In [318]:
df

        Name   Age     Dept   Salary
0      Utibe  30.0       HR  55000.0
1     Bassey  25.0       IT  65000.0
2     Inyang  20.0  Finance  75000.0
3      Henry   NaN       IT  67000.0
4  Happiness  29.0       HR      NaN
5      Hopex  25.0       HR  55000.0

In [319]:
df['Dept'].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [320]:
# HOw many employees in each Department
df['Dept'].value_counts() # Counts the values in a dataset

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [321]:
df['Promoted Salary'] = df['Salary'] * 10
df

        Name   Age     Dept   Salary  Promoted Salary
0      Utibe  30.0       HR  55000.0         550000.0
1     Bassey  25.0       IT  65000.0         650000.0
2     Inyang  20.0  Finance  75000.0         750000.0
3      Henry   NaN       IT  67000.0         670000.0
4  Happiness  29.0       HR      NaN              NaN
5      Hopex  25.0       HR  55000.0         550000.0

## Data Cleaning

In [322]:
# finding all the missing Null values in the dataframe

df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted Salary    1
dtype: int64

In [323]:
# Drop the row with missing values

# df.dropna()

In [324]:
# df.fillna(0) # --> fills the missing values with 0

In [328]:
df['Age'].fillna(df['Age'].mean())

0    30.0
1    25.0
2    20.0
3    25.8
4    29.0
5    25.0
Name: Age, dtype: float64

        Name   Age     Dept   Salary  Promoted Salary
0      Utibe  30.0       HR  55000.0         550000.0
1     Bassey  25.0       IT  65000.0         650000.0
2     Inyang  20.0  Finance  75000.0         750000.0
3      Henry   NaN       IT  67000.0         670000.0
4  Happiness  29.0       HR      NaN              NaN
5      Hopex  25.0       HR  55000.0         550000.0

In [329]:
student = {
    'name': ['Adam', 'Smith', 'Oluremi'],
    'Department': ['IT', 'HR', 'Customer Support']
}

In [330]:
student

{'name': ['Adam', 'Smith', 'Oluremi'],
 'Department': ['IT', 'HR', 'Customer Support']}

In [331]:
student_data = pd.DataFrame(student)

In [332]:
student_data

      name        Department
0     Adam                IT
1    Smith                HR
2  Oluremi  Customer Support