# PANDAS

Pandas lets you load, explore, and analyze data using Python code. It makes the job faster than clicking on Excel sheets..

Pandas gives you two super powers.
- A series --> one column of data (basically a list with labels)
- A DataFrame --> a full table (rows + columns, just like a full spreadsheet of data)

To use Python in a Notebook, you have to import pandas as pd

In [1]:
# import pandas library into the notebook
import pandas as pd # the "as pd"part is just a nickname. So instead of typing pandas everytime, you type pd

## Python Series

A Series is like a single column in a spreadsheet. It is simply a list of values with an index (row labels).

In [2]:
# A simple series of student scores
scores = pd.Series([85, 92, 78, 95, 60], index=['alice', 'bob', 'carol', 'david', 'eve'])

scores

alice    85
bob      92
carol    78
david    95
eve      60
dtype: int64

## Python DataFrame

A DataFrame is a full spreadsheet with multiple columns and multiple rows.

Almost everything you will do in Data Analysis starts with a DataFrame.

In [3]:
# Example: A Class Grade Book

data = {
    'Name' : ['Alice', 'Bob', 'Carol', 'David', 'Eve'],
    'Math' : [85, 92, 78, 95, 60],
    'Science' : [88, 79, 95, 85, 72],
    'English' : [90, 85, 80, 88, 65]
}

df = pd.DataFrame(data) # we convert the dictionary to dataFrame

df

    Name  Math  Science  English
0  Alice    85       88       90
1    Bob    92       79       85
2  Carol    78       95       80
3  David    95       85       88
4    Eve    60       72       65

## Useful Commands in Pandas

Once you have a DataFrame, these are the first things you will always run:

- df.shape (Dispays how many Rows and columns)
- df.columns (Lists all column names)
- df.dtypes (shows the data types of each column)
- df.head() (shows the first 5 rows)
- df.tail() (shows the last 5 rows)
- df.info() (displays the full summary of the DataFrame)
- df.describe (gives a statistical summary of the dataset)

In [4]:
df.shape

(5, 4)

In [5]:
# PRACTICE EXERCISE

data = {
    'Student' : ['Liam', 'Mia', 'Noah', 'Ava', 'James'],
    'Age' : [20, 22, 21, 19, 23],
    'GPA' : [3.5, 3.8, 3.1, 3.9, 2.7],
    'Major' : ['Biology', 'CS', 'Math', 'CS', 'History']
}

df = pd.DataFrame(data)

df

  Student  Age  GPA    Major
0    Liam   20  3.5  Biology
1     Mia   22  3.8       CS
2    Noah   21  3.1     Math
3     Ava   19  3.9       CS
4   James   23  2.7  History

In [6]:
# QUESTION 1
# How many rows and columns does this DataFrame have?

df.shape # Answer: 5 rows and 4 columns

(5, 4)

In [7]:
# QUESTION 2
# What are the names of the columns 

df.columns # --> pandas always wraps column names in its own index object

Index(['Student', 'Age', 'GPA', 'Major'], dtype='str')

In [8]:
# QUESTION 3
# Show only the first 3 rows

df.head(3)

  Student  Age  GPA    Major
0    Liam   20  3.5  Biology
1     Mia   22  3.8       CS
2    Noah   21  3.1     Math

In [9]:
# QUESTION 4
# What Data Type is the GPA Column

df.dtypes  #--> object means text/string, int64 means whole numbers, float64 means decimals.

Student        str
Age          int64
GPA        float64
Major          str
dtype: object

## Loading Real Data into DataFrames

Understanding the anatomy of Pandas DataFrame will save you hours of confusion.

A DataFrame has 3 core components:
- index
- columns
- rows

### The Index
The index is the row label system. By default, it is 0,1,2,3,4,5... but it can be anything; names, dates, IDs. The index is not a column. It lives on the side and its basically used for looking up rows.

### The Columns
Each column has a name. When you select one column, you get a *Series*. That is why series and DataFrame are so Connected.

### The Values (Rows)
The actual data lives in a structure called a Numpy Array under the hood. To see the raw values in the structure, use df.values

In [12]:
df.values

array([['Liam', 20, 3.5, 'Biology'],
       ['Mia', 22, 3.8, 'CS'],
       ['Noah', 21, 3.1, 'Math'],
       ['Ava', 19, 3.9, 'CS'],
       ['James', 23, 2.7, 'History']], dtype=object)

### Data Types
This is one of the most skipped topics for beginners. It causes endless bugs.
Every column in a DataFrame has a dtype (dtype). Pandas needs to know what kind of data each column holds so it knows what operations make sense.
- int64 (whole numbers)
- float64 (decimal numbers)
- object (text)
- bool (true/false)
- datetime64 (dates and times)
- category (repeated labels e.g; male/female)

You can only perform math operations on numeric data types. You can only do text operations on object dtype.
Knowing your dtypes is like knowing the rules of the road before driving.

In [ ]:
# Assessing the datatypes in a dataset

df.dtypes

Student        str
Age          int64
GPA        float64
Major          str
dtype: object