# PANDAS

Pandas is a Python Library built ontop of Numpy. Widely used in DA,DS and ML.

The name Pandas come from Panel Data and has nothing to do with pandas -  the animal

In Pandas, you typically work with Series and DataFrame.
- A series is a 1-dimensional label
- A dataFrame is a 2 dimensional labelled grid or table

In [1]:
import pandas as pd

In [2]:
student = {
    'name' : ['utibe', 'john'],
    'age' : [12, 23],
    'department' : ['it', 'customer care']
}

In [3]:
df = pd.DataFrame(student)

In [4]:
df

    name  age     department
0  utibe   12             it
1   john   23  customer care

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        2 non-null      object
 1   age         2 non-null      int64
 2   department  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

In [7]:
df.columns

Index(['name', 'age', 'department'], dtype='object')

In [10]:
df.dtypes

name          object
age            int64
department    object
dtype: object

In [12]:
df.head()

    name  age     department
0  utibe   12             it
1   john   23  customer care

In [14]:
df.tail()

    name  age     department
0  utibe   12             it
1   john   23  customer care